### PR TITLE
Cancel button style for ionic 1.3 (small but important fix)

### PR DESCRIPTION
**Pull request by sebrojas14**
On ionic 1.3 is necessary to add button-dark class after button-clear, because button-clear sets the color to transparent

### CODE REVIEW

**Comment by sebrojas14** [comment]
Something wrong with this?

**Comment by guylabs** [comment]
Hi

sorry for my delay but I was on a longer trip and now I am working partially. First of all thanks for the contribution! Could you maybe also execute the `build` grunt task such that the `dist` folder gets updated too? And does this change also work with Ionic `1.2.4`? If not we need to postpone it till #189 is done to support Ionic `1.3.x`.

Thanks and regards,

Guy

**Comment by sebrojas14** [comment]
I tried to run the grunt task on my mac but always got an error :S. And yes, should work on 1.2.4, because is only a class added.

**Comment by sebrojas14** [comment]
I can't get the grunt task run...I tried on mac and windows. Getting:
image

**Comment by sebrojas14** [comment]
I removed autofocus behavior because was causing on iOS that an item was autoselectd after open the modal

**Comment by guylabs** [comment]
Hi @sebrojas14 

what kind of Node and NPM version do you have? If it does not work out then I will do the changes by myself when I work on the `0.4.0` version to upgrade to `1.3`.

Thanks and regards,

Guy

**Comment by sebrojas14** [comment]
I have Node 0.12.2 and NPM 2.7.4. Please take a look to https://github.com/Hobbule/ion-autocomplete/ I had to move with my changes because I'm using it in an app. I put this changes and also I using the Ionic Modal Service (is much better)

**Comment by guylabs** [comment]
Hi @sebrojas14 

See #204 for the comments and lets track the issue there and not here. What do you mean with you use the Ionic Modal Service?

Thanks and regards,

Guy

**Comment by brunodeprez** [comment]
Hi guys, this change is important for me as for the moment the Done button is not visible

**Comment by sebrojas14** [comment]
@brunodeprez check out https://github.com/Hobbule/ion-autocomplete

**Comment by guylabs** [comment]
Hi

the master now runs on Ionic `1.3.2` and this will be released in `0.4.0`.

You can test it with the latest master already if you want to.

Thanks and regards,

Guy

**Comment by brunodeprez** [comment]
Just updated to 0.4.0 and the issue is solved!
Thanks hips @guylabs

**Pull request closed without merging**
