### PR TITLE
Feature/loading icon

### PR DESCRIPTION
**Pull request by texh**
Addresses guylabs#12.

Conceptual but seems to work ok.

screenshot_2015-05-09-11-11-48
screenshot_2015-05-09-11-13-21

### CODE REVIEW

**Comment by guylabs** [comment]
Hi Jarrod, 

I think it's a good idea as not all ionic users have a general loading spinner if there is network traffic. Maybe I would remove the `loader` configuration option and just use the `loaderIcon` and if this is set, then the loader will be displayed. Most of the users need a specific loading icon and therefore it would be good to combine this logic into one configuration option. What do you think about it?

And could you maybe add some basic karma tests that the loader is shown if the `loaderIcon` is set and is not shown if not set? I'm sorry but I do not have the time for doing it till tomorrow where I want to do the release of 0.2.1. If you also do not have the time we can move it to 0.2.2.

I will also add the documentation for this new configuration option once this pull request is merged.

Thanks a lot for the contribution!

Regards and have a nice evening,

Guy

**Comment by texh** [comment]
Sounds like a plan.

The reason for the loader parameter was such that it will by default nature of the ionSpinner show a different image on Android/iOS if the directive is used but no icon is specified.
I could add "auto" as an option for loaderIcon though which would achieve the same should someone want it to behave this way.

Will also look at adding a couple of tests when I get the chance but mightn't be able to over the next few days.

I'll be back with the proposed changes at some stage

J

**Comment by guylabs** [comment]
Hi Jarrod,

any news on this?

Regards,

Guy

**Comment by guylabs** [comment]
Closed due inactivity and because the loading spinner has been added to the master. See #12.

**Pull request closed without merging**
